[theme]
base="dark"
backgroundColor="#26324c"
secondaryBackgroundColor="#34484c"

[browser]
gatherUsageStats = false

[server]
enableStaticServing = true

[llm]
ollama_model = "dolphin3:latest"
default_provider = "ollama"

[location]
zip_code = "68164"